services:
  - type: web
    name: go-blogg-cms
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        sync: false
      - key: APP_DEBUG
        sync: false
      - key: APP_URL
        value: https://go-blogg-cms.onrender.com
      - key: DB_CONNECTION
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
